### PR TITLE
namespace and getters and setters added

### PR DESCRIPTION
**Pull request by sboo**

### CODE REVIEW

**Comment by Gormador** [comment]
Hi Ramon,

First of all, thank you for your interest in our php wrapper!
We are open to accept your pull request but, as it involves breaking changes we want to be careful about it, which I'm sure you understand.

So, would you be able go into the details of why requiring it isn't possible in your composer.json?
From what we've seen, you are using PSR-4 in your [composer.json](https://github.com/sboo/laravel5-mailjet/blob/master/composer.json) while still using PSR-0-like folder architecture. Our wrapper uses PSR-0.
Laravel seems fine autoloading packages either way (see [here](http://fideloper.com/laravel-4-application-setup-app-library-autoloading) and [here](http://laravel-tricks.com/tricks/use-composers-psr-4-autoloader-to-put-namespaces-classes-in-laravel-directories)).

Hence the need for a clarification...

Thanks in advance for your reply!

**Comment by sboo** [comment]
Regarding breaking compatibility: you could put it in a higher version number, like 2.0. That would surely prevent conflicts with current installations unless someone required it with dev-master, which is bad practice.

In any kind of project, not namespacing 3rd party packages can hinder your own code and prevent you from naming a class the same name. However, namespacing makes it always clear what comes from a vendor and you can use it in the right context.

You are absolutely right, it works without the namespaces, but it's still advisable and good practice. 

The change to psr-4 might have been a mistake. Please ignore. I can change it back.

Let me know what you would like me to do, in any case, I'm happy to help out.

Cheers,
Ramon

**Comment by sboo** [comment]
I fixed the paths in my package. But that wouldn't interfere with your package anyway. But thanks for attending me to my mistake

**Comment by Gormador** [comment]
Thank you for the followup!
We are doing some testing right now on out end as, again, we want to be extra careful with this.

Regarding the version numbering, we already thought about bumping the major release version to 2.0; it's nice to see that it would make sense to others, too!

Thanks again; we will keep you posted on further development!

**Comment by Gormador** [comment]
Hi @sboo ,

First of all, sorry for the delay in our response.

Now, two things: 
  * we are going to integrate your changes to the wrapper.
  * we won't directly do it through this PR as you requested a merge on our master branch.

Don't worry though, you are going to be duly credited as the main contributor to this version!

This will allow us to make other changes in order to further refine the wrapper, mainly for consistency's sake:
  * Namespace change to "Mailjet\API"
  * Class name change to "Client"

Regarding your Laravel package, it would be better if it `require`s the modified php wrapper (once the 'official' version is live) instead of including it directly. Also, could you put the package under the MIT license?

Thanks again for your interest in Mailjet and your work on integrating it with Laravel.

**Comment by sboo** [comment]
Hi @Gormador ,

Cool, I'm glad I could bring some input into furthering the class. I totally agree with the namespace-choices you made, I think they're perfect.
Once your version is live, I will of course require it, I have no desire to duplicate code for no reason :)

My package is under MIT license (as per composer file). I will add the LICENSE file as well.

Cheers,
Ramon

**Comment by Gormador** [comment]
My bad, I didn't check the composer.json ;-)

You can check the **v2.0.0-dev** version here: https://github.com/mailjet/mailjet-apiv3-php-simple/tree/sboo-master
You've been added to the 'authors' list in the composer.json.

**Comment by sboo** [comment]
@Gormador looks great, I'm looking forward to implement it :)

**Comment by Gormador** [comment]
Hello @sboo !

If you're happy with how your pull request was resolved, feel free to close it.

Of course, don't hesitate to open a new issue if the need were to arise!

**Pull request closed without merging**
