### PR TITLE
 Fix JSON_BIGINT_AS_STRING with PHP >= 5.5

### PR DESCRIPTION
**Pull request by cba85**

### CODE REVIEW

**Comment by arnaudbreton** [comment]
Hey, thanks a lot for your contribution @cba85!

Can you tell us more about it please? Thanks!

**Comment by cba85** [comment]
Hey,

There is a bug with the constant JSON_BIGINT_AS_STRING that was removed from json_decode() in PHP 5.5.

http://stackoverflow.com/questions/19520487/json-bigint-as-string-removed-in-php-5-5

**Comment by arnaudbreton** [comment]
It's still marked as supported on the official documentation: http://php.net/manual/fr/function.json-decode.php

**Comment by cba85** [comment]
Yes you're right, it looks like that was introduced to some Linux distributions due to LICENSE concerns. This problem is due to an affected json-c PECL module.
I fixed the bug using a newer version of the module on my Ubuntu server.

**Comment by arnaudbreton** [comment]
Awesome, glad to hear @cba85. Could you please close this PR if everything's OK? Again, thanks a lot for your contribution, highly appreciated!

**Pull request closed without merging**
