### PR TITLE
fixed rounding error

### PR DESCRIPTION
**Pull request by edwinPhd**
as discussed in issue: https://github.com/mailjet/mailjet-apiv3-php-simple/issues/54

### CODE REVIEW

**Comment by edwinPhd** [comment]
using this
<?php
$int = 13792281593735208;
$arr = array('test' => $int);
$string = json_encode($arr);
$back_array = json_decode($string);
echo number_format($arr['test'],0,'.','');
echo ' : ';
echo number_format($back_array->test,0,'.','');

retuns this:
13792281593735208 : 13792281593735000

**Comment by arnaudbreton** [comment]
Which version of PHP are you using? On my setup (5.5.14 / OSX), it gives `13792281593735208 : 13792281593735208`

**Comment by edwinPhd** [comment]
PHP 5.5.6 

Its what our servers use, so I am pretty much stuck with it. Glad to see that the new version fixes this.

**Comment by arnaudbreton** [comment]
Glad to see it too. With your fix, the result is a string, not an integer, right?

**Comment by edwinPhd** [comment]
yes, which is fine for me.

**Comment by arnaudbreton** [comment]
Ok, thanks. Just checking to evaluate what will be the impacts and how-to tag this release. From your feedback, I would say it's a minor version, 1.0.4. What do you think?

**Comment by edwinPhd** [comment]
definitely minor

**Comment by edwinPhd** [comment]
my luck looks like they fixed it in 5.5.7
https://bugs.php.net/bug.php?id=66707

**Comment by arnaudbreton** [comment]
Glad to hear that! Maybe, we should more give notice to other developers to use at least PHP 5.5.7? Seems like a regression, no?

**Comment by edwinPhd** [comment]
Either let them know 

or we can check the version and run what is required.

if (version_compare(PHP_VERSION, '5.5.9') >= 0) {
$this->_response = json_decode($buffer);
}else{
$this->_response = json_decode($buffer, false, 512, JSON_BIGINT_AS_STRING);
}

(Not sure if the fix was in 5.5.7 or 5.5.9, so going for the safe option)

**Comment by yasen-mailjet** [comment]
I'd go for this formatting:

    $this->_response = version_compare(PHP_VERSION, '5.5.9') >= 0 ? json_decode($buffer) : json_decode($buffer, false, 512, JSON_BIGINT_AS_STRING);

**Comment by edwinPhd** [comment]
Ok, updated the code with the your formatting. Thanks

**Comment by arnaudbreton** [comment]
From my comprehension of things, this issues is very environment specific. Are you using a 32 or 64 bits PHP version?

**Comment by edwinPhd** [comment]
Just checked 32bit. If it is a bit problem then the above will not fix it, we would have to change the line to:
$this->_response = PHP_INT_SIZE > 4 ? json_decode($buffer) : json_decode($buffer, false, 512, JSON_BIGINT_AS_STRING);

 PHP_INT_SIZE  returns 4 in 32 bit, and should be 8 with 64bit.

**Comment by arnaudbreton** [comment]
I haven't found a way to test and old PHP release on OSX to see if it's a version or architecture issue. By luck, could you try this on your side?

**Comment by arnaudbreton** [comment]
Just ran some tests on http://3v4l.org/ (online PHP interpreter, 64 bits only) and the result of your sample is the same from PHP 5.2.1:
 ```
Output for 5.2.1 - 5.6.5, php7@20140507 - 20150201, hhvm-3.3.1 - 3.5.0
13792281593735208 : 13792281593735208
```

Sounds like an architecture issue so your list fix might be the best.

**Comment by edwinPhd** [comment]
updated it to
 $this->_response = PHP_INT_SIZE > 4 ? json_decode($buffer) : json_decode($buffer, false, 512, JSON_BIGINT_AS_STRING);

My only worry is PHP_INT_SIZE, not sure what php version it is valid from.

**Comment by arnaudbreton** [comment]
Yes, I wondered about that too. Actually, a friend of mine (hey @arnaud-lb!) just pointed me to the JSON scanner code in C: https://github.com/php/php-src/blob/master/ext/json/json_scanner.c#L268

Looking at this code, you can see that the `JSON_BIGINT_AS_STRING` option mask is only affecting integer which are overflowing, so there's no need to actually test `PHP_INT_SIZE` since it's already done by the JSON parser.

**Comment by edwinPhd** [comment]
If I understand you correctly we only need
$this->_response = json_decode($buffer, false, 512, JSON_BIGINT_AS_STRING);
but on a 64bit system is a large int returned as a int or string?

**Comment by arnaudbreton** [comment]
It's returned as an integer yes

**Comment by edwinPhd** [comment]
Ok, back to commit 1 again, lol. One learns something new every day.

**Comment by arnaudbreton** [comment]
Yes, right? Thanks for bringing to us this very interesting issue. I'll merge the PR and release a new version of the wrapper. I'll let you know once done.

Cheers!

**Pull request merged**
