### PR TITLE
Fixing tests (PHPUnit) locally

### PR DESCRIPTION
**Pull request by Narno**
* requiring PHPUnit 4.0
* tests autoloading
* enhancing tests code

### CODE REVIEW

**Comment by Gormador** [comment]
Wow you're quick ;-)

We will review your pull request and get back to you! Don't expect us to be as quick as you though... :-D

**Comment by Narno** [comment]
No problem, take your time! :-)

**Comment by Narno** [comment]
API keys can be configured with dedicated ```env``` tags in ```phpunit.xml``` config file:
```
<env name="API_KEY" value="API_KEY"/>
<env name="API_SECRET_KEY" value="API_SECRET_KEY"/>
```

**Comment by GuillaumeBadi** [comment]
### Hey @Narno :airplane:

We just released a [new PHP API wrapper](https://github.com/mailjet/mailjet-apiv3-php).
It is now more PHP-ish (including namespace, PSR-0 compliance, and globally a better architecture).
All it requires is PHP 5.4

In addition to our [API Guides](http://dev.mailjet.com/guides/?php), we would be happy to help you get started with it.

Guillaume, from Mailjet!

**Pull request closed without merging**
