### PR TITLE
Switching to PSR-4 and fixing tests

### PR DESCRIPTION
**Pull request by Narno**

### CODE REVIEW

**Comment by Narno** [comment]
Tested with PHPUnit 4.5.1:
>Time: 2.92 seconds, Memory: 4.50Mb
> 
> OK (3 tests, 3 assertions)

**Comment by Gormador** [comment]
Hi @Narno 

First of all, thank you for your interest in Mailjet!

We are taking note of your pull requests.
However, have you checked the [sboo-master branch](https://github.com/Narno/mailjet-apiv3-php-simple/tree/sboo-master) on this very repo? It doesn't make use of the PSR-4 standard as it still isn't widely spread, but we introduced (thanks to PR #73) namespacing (and generally a better code structure) as well as support for upcoming features regarding the contact & contactslist resources.

The same applies to #82 :-)

**Comment by Narno** [comment]
Holy shit! :-/
Lot of wasted time: I'll have to check each of the branches before...

You should add a note about this in the readme of the master branch.

**Comment by Gormador** [comment]
Don't worry, it's still practice :-) Also, we are more than welcome for any suggestion on the dev version !

Regarding that note, we didn't put one as it could mislead people into thinking that the dev version would be the absolute way to go, which isn't the case and could lead to confusion.

**Comment by Narno** [comment]
No problem, I will contribute to the new version ;-)

**Pull request closed without merging**
